// WATCHOUT 7 User Guide - Table of Contents Data
// Auto-generated by build-content.js - DO NOT EDIT DIRECTLY
// Edit the markdown files in /content instead

// SVG Icons (Lucide-style)
const icons = {
    book: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>`,
    settings: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>`,
    layout: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>`,
    monitor: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line></svg>`,
    film: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect><line x1="7" y1="2" x2="7" y2="22"></line><line x1="17" y1="2" x2="17" y2="22"></line><line x1="2" y1="12" x2="22" y2="12"></line><line x1="2" y1="7" x2="7" y2="7"></line><line x1="2" y1="17" x2="7" y2="17"></line><line x1="17" y1="17" x2="22" y2="17"></line><line x1="17" y1="7" x2="22" y2="7"></line></svg>`,
    clock: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>`,
    play: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>`,
    sliders: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>`,
    globe: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>`,
    keyboard: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2" ry="2"></rect><path d="M6 8h.001"></path><path d="M10 8h.001"></path><path d="M14 8h.001"></path><path d="M18 8h.001"></path><path d="M8 12h.001"></path><path d="M12 12h.001"></path><path d="M16 12h.001"></path><path d="M7 16h10"></path></svg>`,
    alertCircle: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>`,
    fileText: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>`,
    link: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>`
};

// Get icon SVG by name
function getIcon(iconName) {
    return icons[iconName] || icons.fileText;
}

const tocData = [
    {
        "level": 1,
        "title": "1. Getting Started",
        "page": 1,
        "icon": "book"
    },
    {
        "level": 2,
        "title": "Welcome To Watchout 7",
        "page": 1,
        "description": "WATCHOUT 7 is the latest evolution of Dataton's award-winning multi-display production and playback system. Designed ...",
        "group": "First Steps",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "System Requirements",
        "page": 2,
        "description": "WATCHOUT 7 requires a Windows-based computer with modern hardware to deliver optimal performance. The requirements di...",
        "group": "First Steps",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Installing Watchout",
        "page": 3,
        "description": "Setting up WATCHOUT represents the first step toward creating your show. The installation process is straightforward,...",
        "group": "First Steps",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Launching The Application",
        "page": 4,
        "description": "Once WATCHOUT is installed, you are ready to launch the software. How you launch it depends on whether you are workin...",
        "group": "Setup and Configuration",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Network Configuration",
        "page": 5,
        "description": "Establishing a robust and properly configured network is critical for WATCHOUT 7. The system relies on the network no...",
        "group": "Setup and Configuration",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Quick Start Tutorial",
        "page": 6,
        "description": "This tutorial walks you through building your first WATCHOUT 7 show from scratch. By the end, you will have a display...",
        "group": "Your First Show",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Architectural Differences Watchout 6 Vs 7",
        "page": 7,
        "description": "If you have been running shows with WATCHOUT 6, much of what you know still applies — timelines, cues, the Stage meta...",
        "group": "Your First Show",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 1,
        "title": "2. Working with Shows",
        "page": 1,
        "icon": "fileText"
    },
    {
        "level": 2,
        "title": "Creating A New Show",
        "page": 1,
        "description": "Every WATCHOUT project begins with creating a show. A show is the container for all your displays, timelines, cues, a...",
        "group": "Essentials",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Opening Existing Shows",
        "page": 2,
        "description": "Most of your time in WATCHOUT will be spent working on shows that already exist—whether you created them yourself in ...",
        "group": "Essentials",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Saving Your Work",
        "page": 3,
        "description": "Regular saving is fundamental to any production workflow. WATCHOUT provides several save options to accommodate diffe...",
        "group": "Essentials",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Show Properties",
        "page": 4,
        "description": "Every show carries a set of properties that define how it behaves globally—settings that affect all timelines, all di...",
        "group": "Show Configuration",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Show Consolidation",
        "page": 5,
        "description": "In a typical WATCHOUT workflow, your show file references media assets stored on an Asset Manager. The show file itse...",
        "group": "Archiving and Auditing",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Show Information",
        "page": 6,
        "description": "The Show Information section provides a statistical overview of the current show, giving you a quick summary of its c...",
        "group": "Archiving and Auditing",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 1,
        "title": "3. Displays and Outputs",
        "page": 1,
        "icon": "monitor"
    },
    {
        "level": 2,
        "title": "Adding Displays",
        "page": 1,
        "description": "A display is the fundamental output unit in WATCHOUT. It maps a rectangular pixel area on the stage to a physical out...",
        "group": "Essentials",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Virtual Displays",
        "page": 2,
        "description": "A virtual display renders cues to an internal texture buffer instead of a physical output connector. Think of it as a...",
        "group": "Core Display Types",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "3d Mapping Projectors",
        "page": 3,
        "description": "3D projectors are used to project media content onto real-world three-dimensional surfaces such as buildings, stage s...",
        "group": "Core Display Types",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Display Grid Setup",
        "page": 4,
        "description": "Display grid is an array of tiled output devices — such as LED panels, monitors, or projectors — arranged in a unifor...",
        "group": "Essentials",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Display Properties",
        "page": 5,
        "description": "Display Properties control how each display is named, placed, routed, rendered, and calibrated. In practice, this pan...",
        "group": "Essentials",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Edge Blending",
        "page": 6,
        "description": "Edge blending is the process of smoothing the overlap region between two or more adjacent display outputs so that the...",
        "group": "Geometry Correction and Blending",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Warp Geometry",
        "page": 7,
        "description": "Warp geometry is WATCHOUT's system for correcting the shape of rendered output so that it aligns with the physical su...",
        "group": "Geometry Correction and Blending",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Display Masks",
        "page": 8,
        "description": "Display masks control which pixels on a display are visible and how their edges are shaped. Unlike warp geometry, whi...",
        "group": "Geometry Correction and Blending",
        "groupOrder": 2,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Sdi Output",
        "page": 9,
        "description": "SDI (Serial Digital Interface) is a professional video transport standard used widely in broadcast, live event, and A...",
        "group": "Core Display Types",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "HDR and Color Management",
        "page": 10,
        "description": "WATCHOUT includes a color-managed rendering pipeline that handles the full chain from media decode through compositin...",
        "group": "Color, Calibration, and Diagnostics",
        "groupOrder": 3,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Test Patterns",
        "page": 11,
        "description": "Test patterns are built-in diagnostic output modes rendered directly by the Runner on a per-display basis. They are i...",
        "group": "Color, Calibration, and Diagnostics",
        "groupOrder": 3,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Display Calibration",
        "page": 12,
        "description": "Calibration is the process of aligning WATCHOUT's rendered output to the physical reality of the display surface. Thi...",
        "group": "Color, Calibration, and Diagnostics",
        "groupOrder": 3,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Compression Fundamentals",
        "page": 13,
        "description": "As display resolutions, frame rates, and color depths continue to increase, the amount of raw pixel data in a product...",
        "group": "Color, Calibration, and Diagnostics",
        "groupOrder": 3,
        "groupItemOrder": 3
    },
    {
        "level": 1,
        "title": "4. Assets & Asset Manager",
        "page": 1,
        "icon": "film"
    },
    {
        "level": 2,
        "title": "Asset Manager",
        "page": 1,
        "description": "The Asset Manager is the centralized service that handles the entire lifecycle of media in a WATCHOUT 7 show — from i...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Asset Types",
        "page": 2,
        "description": "WATCHOUT 7 classifies every asset into a specific type that determines how it is optimized, how it behaves on the tim...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Asset Properties",
        "page": 3,
        "description": "The Properties panel displays detailed metadata for any selected asset, adapting its layout to show only the fields r...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Formats & Codecs",
        "page": 4,
        "description": "Choosing the right source format and optimization codec is one of the most consequential decisions in show design. Th...",
        "group": "Media Formats and Creation",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "SVG Shapes",
        "page": 5,
        "description": "WATCHOUT 7 includes a built-in shape editor that lets you create vector-based assets — rectangles, ellipses, and text...",
        "group": "Media Formats and Creation",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Dynamic Assets",
        "page": 6,
        "description": "A dynamic asset is a named container that holds versioned content, allowing you to swap media — different language tr...",
        "group": "Advanced Asset Workflows",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Image Sequences",
        "page": 7,
        "description": "An image sequence is a series of numbered image files — such as render0001.png, render0002.png, render0003.png — that...",
        "group": "Media Formats and Creation",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Web User Interface",
        "page": 8,
        "description": "The Asset Manager includes a built-in web server that provides a browser-based interface for uploading and managing a...",
        "group": "Advanced Asset Workflows",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Asset Watcher",
        "page": 9,
        "description": "The Asset Watcher monitors designated folders on the Asset Manager node's file system and automatically imports new o...",
        "group": "Advanced Asset Workflows",
        "groupOrder": 2,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Asset Transfer",
        "page": 10,
        "description": "When a show goes online, WATCHOUT automatically distributes optimized media to every display server (Runner) in the s...",
        "group": "Advanced Asset Workflows",
        "groupOrder": 2,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Asset Manager Settings",
        "page": 11,
        "description": "The Asset Manager Settings dialog is the central control point for how assets are optimized, what codecs are used, an...",
        "group": "Settings and Data Management",
        "groupOrder": 3,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Import, Export, and Mapping",
        "page": 12,
        "description": "Export and import let you package a show's optimized assets into a portable archive and bring them into a different W...",
        "group": "Settings and Data Management",
        "groupOrder": 3,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Importing GDTF Files",
        "page": 13,
        "description": "GDTF (General Device Type Format) is an open standard for describing intelligent lighting fixtures. Importing a GDTF ...",
        "group": "Settings and Data Management",
        "groupOrder": 3,
        "groupItemOrder": 2
    },
    {
        "level": 1,
        "title": "5. Timeline and Cues",
        "page": 1,
        "icon": "clock"
    },
    {
        "level": 2,
        "title": "Understanding The Timeline",
        "page": 1,
        "description": "The timeline is the central workspace in WATCHOUT 7 where every piece of show content is placed, sequenced, and contr...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Adding Media Cues",
        "page": 2,
        "description": "A media cue is the primary visual or audible element on a WATCHOUT timeline-it is what the audience actually sees and...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Working With Layers",
        "page": 3,
        "description": "Layers are the primary organizational and compositing structure within a WATCHOUT timeline. Every media cue, control ...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Adjusting Timing",
        "page": 4,
        "description": "Precise timing is central to show quality — a single frame of misalignment between projectors or a late audio cue can...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Control Cues",
        "page": 5,
        "description": "Control cues are the mechanism for orchestrating timeline playback states across a WATCHOUT show. While media cues pl...",
        "group": "Cue Types",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Marker Cues",
        "page": 6,
        "description": "Marker cues (also called comment cues) are point-in-time timeline annotations used for organization, operator guidanc...",
        "group": "Cue Types",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Output Cues",
        "page": 7,
        "description": "Output cues are the mechanism for sending external messages synchronized with timeline playback. When the playhead re...",
        "group": "Cue Types",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Variables and Variable Cues",
        "page": 8,
        "description": "Variables are the bridge between external inputs and show behavior in WATCHOUT. They store numeric values that can be...",
        "group": "Cue Types",
        "groupOrder": 1,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "ArtNet Fixture Cues",
        "page": 9,
        "description": "ArtNet fixture cues are WATCHOUT's mechanism for controlling DMX lighting fixtures directly from the timeline, combin...",
        "group": "Cue Types",
        "groupOrder": 1,
        "groupItemOrder": 4
    },
    {
        "level": 2,
        "title": "Compositions",
        "page": 10,
        "description": "Compositions are nested timeline units that allow you to group multiple cues into a single, self-contained entity. A ...",
        "group": "Compositions and Organization",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Cue Sets and Variants",
        "page": 11,
        "description": "Cue Sets allow you to create multiple named variants of media content for the same cue, and switch between them at ru...",
        "group": "Compositions and Organization",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Media Snapshots",
        "page": 12,
        "description": "Media Snapshots allow you to save the current property state of selected cues as a named preset, and later recall tha...",
        "group": "Compositions and Organization",
        "groupOrder": 2,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Stacking Order",
        "page": 13,
        "description": "When multiple cues overlap on the same display area, WATCHOUT needs to determine which content appears in front of (o...",
        "group": "Compositions and Organization",
        "groupOrder": 2,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Timeline Triggers and Expressions",
        "page": 14,
        "description": "Timeline triggers are expression-based rules that automate playback state changes, allowing timelines to start, pause...",
        "group": "Automation and Advanced Workflows",
        "groupOrder": 3,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Blind Edit Mode",
        "page": 15,
        "description": "Blind Edit mode lets you make changes to a timeline's cues and properties in isolation, without those changes immedia...",
        "group": "Automation and Advanced Workflows",
        "groupOrder": 3,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Insert and Delete Time",
        "page": 16,
        "description": "The Insert/Delete Time operation shifts cues in bulk by inserting or removing a time range at a specific point on a t...",
        "group": "Automation and Advanced Workflows",
        "groupOrder": 3,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Conditional Cues",
        "page": 17,
        "description": "Any cue in WATCHOUT can have a condition attached that controls whether it is active during playback. For media cues,...",
        "group": "Automation and Advanced Workflows",
        "groupOrder": 3,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Cues Window",
        "page": 18,
        "description": "The Cues Window provides a unified, searchable list of every cue across all timelines and compositions in a WATCHOUT ...",
        "group": "Automation and Advanced Workflows",
        "groupOrder": 3,
        "groupItemOrder": 4
    },
    {
        "level": 2,
        "title": "Output Types Overview",
        "page": 19,
        "description": "WATCHOUT provides five output types for sending information to external systems, covering string-based network messag...",
        "group": "Output Reference",
        "groupOrder": 4,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "6. Effects and Tweens",
        "page": 1,
        "icon": "sliders"
    },
    {
        "level": 2,
        "title": "Understanding Tweens",
        "page": 1,
        "description": "Tweens are time-based value changes attached to cues. Every visual and audio property of a cue that can change over t...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Position and Movement",
        "page": 2,
        "description": "Position tweens animate where a cue appears on Stage over time. By defining a path of positions across the cue's dura...",
        "group": "Transform Effects",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Scale and Size",
        "page": 3,
        "description": "Scale tweens animate the size of a cue over time by controlling horizontal and vertical scaling independently. Whethe...",
        "group": "Transform Effects",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Rotation Effects",
        "page": 4,
        "description": "Rotation tweens control the orientation of a cue over time, enabling everything from simple 2D spins to full 3D persp...",
        "group": "Transform Effects",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Opacity and Fades",
        "page": 5,
        "description": "Opacity controls how transparent or visible a cue is on Stage. WATCHOUT provides two distinct mechanisms for controll...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Cropping",
        "page": 6,
        "description": "Crop tweens animate the visible bounds of a cue, progressively hiding content from any edge. Cropping is one of the m...",
        "group": "Visual Effects",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Color Adjustments",
        "page": 7,
        "description": "Color adjustment tweens let you animate tonal and channel-level color properties directly on individual cues. WATCHOU...",
        "group": "Visual Effects",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Blur Effects",
        "page": 8,
        "description": "WATCHOUT provides a Gaussian Blur tween for softening and defocusing cue content over time. Blur is a versatile creat...",
        "group": "Visual Effects",
        "groupOrder": 2,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Audio Volume",
        "page": 9,
        "description": "The Volume tween automates the loudness of cues that contain audio content. Whether you need music fade-ins, voice-ov...",
        "group": "Audio",
        "groupOrder": 3,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Corner Pinning",
        "page": 10,
        "description": "Corner pinning is a per-cue distortion effect that lets you independently reposition each of the four corners of a me...",
        "group": "Advanced Effects",
        "groupOrder": 4,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Linear Wipe",
        "page": 11,
        "description": "Linear Wipe is a transition effect that progressively reveals or hides a cue's content using a straight-line boundary...",
        "group": "Advanced Effects",
        "groupOrder": 4,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Blend Modes",
        "page": 12,
        "description": "Every media cue in WATCHOUT has a Blend Mode property that determines how its rendered pixels are composited with the...",
        "group": "Visual Effects",
        "groupOrder": 2,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Frame Blending",
        "page": 13,
        "description": "Frame Blending is a per-cue option that smooths video playback when the source media's native frame rate does not mat...",
        "group": "Advanced Effects",
        "groupOrder": 4,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Chroma Key",
        "page": 14,
        "description": "Chroma Key is a per-cue compositing technique that removes a specific color from a cue's rendered output, making thos...",
        "group": "Advanced Effects",
        "groupOrder": 4,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Key and Fill",
        "page": 15,
        "description": "Key & Fill is a layer-level compositing feature that uses the content of one layer (the key layer) to generate a tran...",
        "group": "Advanced Effects",
        "groupOrder": 4,
        "groupItemOrder": 4
    },
    {
        "level": 2,
        "title": "Tween Expressions",
        "page": 16,
        "description": "Tween expressions allow any tween property — position, opacity, scale, color adjustments, and more — to be driven dyn...",
        "group": "Advanced Effects",
        "groupOrder": 4,
        "groupItemOrder": 5
    },
    {
        "level": 1,
        "title": "7. Playback",
        "page": 1,
        "icon": "play"
    },
    {
        "level": 2,
        "title": "Starting and Stopping",
        "page": 1,
        "description": "Playback in WATCHOUT is controlled independently per timeline. Each timeline in your show has its own playback state ...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Preview Mode",
        "page": 2,
        "description": "The Stage window in WATCHOUT is your primary tool for previewing show content before it reaches the audience. There i...",
        "group": "Core Concepts",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Connecting to Display Servers",
        "page": 3,
        "description": "A WATCHOUT system becomes a multi-machine installation when Producer connects to one or more display servers (Runners...",
        "group": "Going Live",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Going Online",
        "page": 4,
        "description": "WATCHOUT 7 is designed as an always-connected system. Unlike earlier versions of WATCHOUT that had distinct \"offline\"...",
        "group": "Going Live",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Running Your Show",
        "page": 5,
        "description": "Running a show reliably is about establishing repeatable procedures that you follow before, during, and after every p...",
        "group": "Show Operation",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "8. The Interface",
        "page": 1,
        "icon": "layout"
    },
    {
        "level": 2,
        "title": "Main Window Overview",
        "page": 1,
        "description": "The WATCHOUT 7 Producer interface is a multi-window workspace where every major function — stage layout, timeline edi...",
        "group": "Overview",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "The Stage Window",
        "page": 2,
        "description": "The Stage is the visual canvas of WATCHOUT 7 — a spatial representation of all your displays and the content position...",
        "group": "Window Reference",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "The Timeline Window",
        "page": 3,
        "description": "The Timeline is where you orchestrate your show — arranging media in time, adding control cues, shaping animations wi...",
        "group": "Window Reference",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "The Cue List Window",
        "page": 4,
        "description": "The Cue List window provides a flat, tabular view of all cues across every timeline in your show. While the Timeline ...",
        "group": "Window Reference",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "The Assets Window",
        "page": 5,
        "description": "The Assets window is your media library — the central place for managing all images, videos, audio files, 3D models, ...",
        "group": "Window Reference",
        "groupOrder": 1,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "The Properties Panel",
        "page": 6,
        "description": "The Properties panel is a context-sensitive inspector that displays settings for whatever is currently selected in th...",
        "group": "Window Reference",
        "groupOrder": 1,
        "groupItemOrder": 4
    },
    {
        "level": 2,
        "title": "The Nodes Window",
        "page": 7,
        "description": "The Nodes window is where you discover, monitor, and manage the WATCHOUT computers on your network. Every machine run...",
        "group": "Window Reference",
        "groupOrder": 1,
        "groupItemOrder": 5
    },
    {
        "level": 2,
        "title": "The Devices Window",
        "page": 8,
        "description": "The Devices window manages the output devices in your show — displays, virtual displays, audio devices, and capture s...",
        "group": "Window Reference",
        "groupOrder": 1,
        "groupItemOrder": 6
    },
    {
        "level": 2,
        "title": "Customizing Your Workspace",
        "page": 9,
        "description": "WATCHOUT 7's interface is built around independent, freely positioned windows that you arrange to suit your workflow....",
        "group": "Customization",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "9. Network Setup",
        "page": 1,
        "icon": "globe"
    },
    {
        "level": 2,
        "title": "Network Overview",
        "page": 1,
        "description": "WATCHOUT 7 is a distributed system. Rather than running everything on a single computer, WATCHOUT spreads its workloa...",
        "group": "Architecture and Basics",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Display Servers",
        "page": 2,
        "description": "A display server is any machine in your WATCHOUT network that runs the Runner service and is responsible for renderin...",
        "group": "Architecture and Basics",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Connecting Devices",
        "page": 3,
        "description": "In WATCHOUT, the physical outputs that render your show — displays, audio devices, and capture sources — are not tied...",
        "group": "Architecture and Basics",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Firewall Configuration",
        "page": 4,
        "description": "WATCHOUT nodes communicate over the network using a combination of UDP and TCP protocols for discovery, playback sync...",
        "group": "Protocols and Services",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "NDI Video Sources",
        "page": 5,
        "description": "WATCHOUT 7 integrates with NDI (Network Device Interface) for both video input and video output over standard Etherne...",
        "group": "Protocols and Services",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Dante Audio",
        "page": 6,
        "description": "WATCHOUT supports Dante as an audio output device type for professional networked audio routing. Dante (Digital Audio...",
        "group": "Protocols and Services",
        "groupOrder": 1,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Node Management and Maintenance",
        "page": 7,
        "description": "Once your WATCHOUT network is running, the Nodes window in Producer serves as your central control point for managing...",
        "group": "Maintenance and Management",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Remote File Access",
        "page": 8,
        "description": "WATCHOUT allows Producer to browse, upload, and manage files on remote nodes across the network. This enables central...",
        "group": "Maintenance and Management",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Working Directory Management",
        "page": 9,
        "description": "Every WATCHOUT node has a working directory — the location on disk where the node stores essential runtime data, incl...",
        "group": "Maintenance and Management",
        "groupOrder": 2,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Software Updates",
        "page": 10,
        "description": "WATCHOUT provides a built-in mechanism for pushing software updates from Producer to remote nodes over the network. T...",
        "group": "Maintenance and Management",
        "groupOrder": 2,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Time Synchronization",
        "page": 11,
        "description": "Frame-accurate multi-display playback is one of WATCHOUT's core capabilities, and it depends on all nodes sharing a p...",
        "group": "Protocols and Services",
        "groupOrder": 1,
        "groupItemOrder": 4
    },
    {
        "level": 2,
        "title": "Capture Sources",
        "page": 12,
        "description": "WATCHOUT 7 supports four capture technologies for bringing live video into your show: NDI, Spout, Deltacast, and Medi...",
        "group": "Protocols and Services",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 1,
        "title": "10. External Control",
        "page": 1,
        "icon": "radio"
    },
    {
        "level": 2,
        "title": "External Control Overview",
        "page": 1,
        "description": "WATCHOUT can be controlled by a wide range of external devices and systems — lighting consoles, show controllers, tra...",
        "group": "Foundations",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Variables and Inputs",
        "page": 2,
        "description": "Variables are the central mechanism through which all external control reaches WATCHOUT's rendering engine. Every ext...",
        "group": "Foundations",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "OSC Protocol",
        "page": 3,
        "description": "Open Sound Control (OSC) is a flexible, message-based protocol widely used in media servers, show controllers, and cr...",
        "group": "Primary Protocols",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "MIDI Bridge",
        "page": 4,
        "description": "The MIDI Bridge is a standalone service that receives MIDI messages from a connected MIDI device and forwards them as...",
        "group": "Specialized Protocols",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "LTC Bridge",
        "page": 5,
        "description": "The LTC Bridge is a standalone service that decodes Linear Time Code (LTC) from an audio input and uses it to synchro...",
        "group": "Specialized Protocols",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "HTTP REST API",
        "page": 6,
        "description": "WATCHOUT exposes an HTTP API for programmatic show control, monitoring, and integration with third-party systems. Thi...",
        "group": "Primary Protocols",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "ArtNet Input",
        "page": 7,
        "description": "WATCHOUT can receive ArtNet DMX data over the network and map incoming DMX channel values to show variables. This all...",
        "group": "Primary Protocols",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "PosiStageNet",
        "page": 8,
        "description": "PosiStageNet (PSN) is an open protocol for transmitting real-time 3D position data from tracking systems over a netwo...",
        "group": "Specialized Protocols",
        "groupOrder": 2,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "MIDI Show Control",
        "page": 9,
        "description": "MIDI Show Control (MSC) is an industry-standard protocol for controlling show equipment using a defined set of comman...",
        "group": "Specialized Protocols",
        "groupOrder": 2,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "WATCHOUT 6 Protocol",
        "page": 10,
        "description": "WATCHOUT 7 includes a backward-compatible WATCHOUT 6 command interface. It is intended for existing integrations (Cre...",
        "group": "Specialized Protocols",
        "groupOrder": 2,
        "groupItemOrder": 4
    },
    {
        "level": 1,
        "title": "11. Keyboard Shortcuts",
        "page": 1,
        "icon": "keyboard"
    },
    {
        "level": 2,
        "title": "File Operations",
        "page": 1,
        "description": "These are the primary default shortcuts for show-file work.",
        "group": "Input and Editing",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Edit Commands",
        "page": 2,
        "description": "These shortcuts are context-sensitive and operate on the active edit target.",
        "group": "Input and Editing",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Stage Navigation",
        "page": 3,
        "description": "Use these shortcuts to frame, scale, and nudge content quickly in Stage workflows.",
        "group": "Navigation and Playback",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Timeline Controls",
        "page": 4,
        "description": "These shortcuts are central to timeline operation and cue management.",
        "group": "Navigation and Playback",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Tween Shortcuts",
        "page": 5,
        "description": "Tween shortcuts toggle common animation/effect tracks on selected cues.",
        "group": "Effects and Layout",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Window Management",
        "page": 6,
        "description": "These shortcuts help you move quickly between WATCHOUT windows and layout presets.",
        "group": "Effects and Layout",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Xbox Controller",
        "page": 7,
        "description": "You can use a standard Xbox-type game controller to adjust warp points more quickly and intuitively in WATCHOUT.",
        "group": "Hardware Input",
        "groupOrder": 4,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Property Editing",
        "page": 8,
        "description": "These shortcuts apply when editing properties in the Properties panel.",
        "group": "Properties and Tables",
        "groupOrder": 3,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Table Views",
        "page": 9,
        "description": "These shortcuts apply inside table-style views such as the Cue List, Assets, and Variables windows.",
        "group": "Properties and Tables",
        "groupOrder": 3,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Display & Warp",
        "page": 10,
        "description": "These shortcuts apply when working in the Warp editor on a display.",
        "group": "Hardware Input",
        "groupOrder": 4,
        "groupItemOrder": 1
    },
    {
        "level": 1,
        "title": "12. Troubleshooting",
        "page": 1,
        "icon": "alertCircle"
    },
    {
        "level": 2,
        "title": "Common Issues",
        "page": 1,
        "description": "This section covers high-frequency problems seen during setup and rehearsal.",
        "group": "Common Issues",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Performance Tips",
        "page": 2,
        "description": "Performance issues are usually a combination of media complexity, output load, and node configuration.",
        "group": "By Category",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Display Problems",
        "page": 3,
        "description": "When a display misbehaves, diagnose in this order: routing, output mode, geometry, then content.",
        "group": "By Category",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Network Issues",
        "page": 4,
        "description": "Most network failures fall into discovery, firewall, or host-alias consistency problems.",
        "group": "By Category",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Media Playback Issues",
        "page": 5,
        "description": "Playback errors usually come from media format compatibility, missing data, or timing/resource pressure.",
        "group": "By Category",
        "groupOrder": 1,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Feedback Reports",
        "page": 6,
        "description": "A feedback report is a compressed diagnostic archive that bundles logs, system information, and optionally the curren...",
        "group": "Getting Support",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Getting Help",
        "page": 7,
        "description": "When escalation is needed, gather diagnostics first so support can reproduce and resolve quickly.",
        "group": "Getting Support",
        "groupOrder": 2,
        "groupItemOrder": 1
    },
    {
        "level": 1,
        "title": "13. Glossary",
        "page": 1,
        "icon": "book"
    },
    {
        "level": 1,
        "title": "14. Legal",
        "page": 1,
        "icon": "fileText"
    }
];

// Process TOC data into hierarchical structure
function processHierarchy() {
    const chapters = [];
    let currentChapter = null;

    tocData.forEach((item) => {
        if (item.level === 1) {
            const isDisabled = typeof wikiConfig !== 'undefined' && 
                wikiConfig.disabledChapters && 
                wikiConfig.disabledChapters.includes(item.title);

            currentChapter = {
                ...item,
                disabled: isDisabled,
                subsections: []
            };
            chapters.push(currentChapter);
        } else if (item.level === 2 && currentChapter) {
            currentChapter.subsections.push(item);
        }
    });

    return chapters;
}

const chaptersData = processHierarchy();
