// WATCHPAX 50 User Guide - Table of Contents Data
// Auto-generated by build-content.js - DO NOT EDIT DIRECTLY
// Edit the markdown files in /content instead

// SVG Icons (Lucide-style)
const icons = {
    book: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>`,
    settings: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>`,
    layout: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>`,
    link: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>`,
    fileText: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>`
};

function getIcon(iconName) {
    return icons[iconName] || icons.fileText;
}

const tocData = [
    {
        "level": 1,
        "title": "1. Introduction",
        "page": 1,
        "icon": "book"
    },
    {
        "level": 2,
        "title": "Welcome to WATCHPAX 50",
        "page": 1,
        "description": "WATCHPAX 50 User's Guide — your complete reference for the Dataton WATCHPAX 50 dedicated media server.",
        "group": "Overview",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Introduction to WATCHPAX 50",
        "page": 2,
        "description": "WATCHPAX 50 is a dedicated media server for use with Dataton WATCHOUT.",
        "group": "Overview",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Accessories",
        "page": 3,
        "description": "A summary of items included with the WATCHPAX 50 and accessories available separately.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Dimensions",
        "page": 4,
        "description": "Physical dimensions and weight of the WATCHPAX 50 unit.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Power",
        "page": 5,
        "description": "Power inlet specifications for the WATCHPAX 50.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Start Up Screen",
        "page": 6,
        "description": "The startup screen displayed when the WATCHPAX 50 powers on.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Environmental",
        "page": 7,
        "description": "Operating and storage conditions for the WATCHPAX 50.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 4
    },
    {
        "level": 2,
        "title": "Connectors",
        "page": 8,
        "description": "Overview of the WATCHPAX 50 front and rear panel connectors.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 5
    },
    {
        "level": 2,
        "title": "Media Server Operating System",
        "page": 9,
        "description": "The operating system in WATCHPAX 50 has been optimized and licensed for this specific media server configuration.",
        "group": "Software",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "2. Installation and Operation",
        "page": 1,
        "icon": "settings"
    },
    {
        "level": 2,
        "title": "Before Using Your WATCHPAX 50",
        "page": 1,
        "description": "Please read the manual thoroughly before operation.",
        "group": "Getting Started",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Ventilation",
        "page": 2,
        "description": "Airflow is critical for the correct operation of WATCHPAX 50.",
        "group": "Getting Started",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Installation",
        "page": 3,
        "description": "Instructions for installing the WATCHPAX 50.",
        "group": "Getting Started",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Quick Start",
        "page": 4,
        "description": "A brief guide to getting your WATCHPAX 50 up and running.",
        "group": "Operation",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Reset WATCHPAX 50",
        "page": 5,
        "description": "Instructions for resetting the WATCHPAX 50.",
        "group": "Operation",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 1,
        "title": "3. Synchronization",
        "page": 1,
        "icon": "link"
    },
    {
        "level": 2,
        "title": "EDID Emulation",
        "page": 1,
        "description": "EDID emulation ensures consistent display identification across all connected outputs.",
        "group": "Configuration",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "4. Warranty, Conformity and Disposal",
        "page": 1,
        "icon": "fileText"
    },
    {
        "level": 2,
        "title": "Limited Warranty",
        "page": 1,
        "description": "DATATON AB warrants this hardware product against defects in materials and workmanship.",
        "group": "Legal",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Declaration of Conformity",
        "page": 2,
        "description": "Dataton AB hereby declares that the WATCHPAX 50 complies with the relevant standards.",
        "group": "Legal",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Disposal",
        "page": 3,
        "description": "Only for European Union and EEA (Norway, Iceland and Liechtenstein).",
        "group": "Legal",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 1,
        "title": "5. Glossary",
        "page": 1,
        "icon": "fileText"
    }
];

function processHierarchy() {
    const chapters = [];
    let currentChapter = null;

    tocData.forEach((item) => {
        if (item.level === 1) {
            const isDisabled = typeof wikiConfig !== 'undefined' &&
                wikiConfig.disabledChapters &&
                wikiConfig.disabledChapters.includes(item.title);

            currentChapter = {
                ...item,
                disabled: isDisabled,
                subsections: []
            };
            chapters.push(currentChapter);
        } else if (item.level === 2 && currentChapter) {
            currentChapter.subsections.push(item);
        }
    });

    return chapters;
}

const chaptersData = processHierarchy();
