// WATCHPAX 64 User Guide - Table of Contents Data
// Auto-generated by build-content.js - DO NOT EDIT DIRECTLY
// Edit the markdown files in /content instead

// SVG Icons (Lucide-style)
const icons = {
    book: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>`,
    settings: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>`,
    layout: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>`,
    monitor: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line></svg>`,
    film: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect><line x1="7" y1="2" x2="7" y2="22"></line><line x1="17" y1="2" x2="17" y2="22"></line><line x1="2" y1="12" x2="22" y2="12"></line><line x1="2" y1="7" x2="7" y2="7"></line><line x1="2" y1="17" x2="7" y2="17"></line><line x1="17" y1="17" x2="22" y2="17"></line><line x1="17" y1="7" x2="22" y2="7"></line></svg>`,
    clock: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>`,
    play: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>`,
    sliders: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>`,
    globe: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>`,
    keyboard: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2" ry="2"></rect><path d="M6 8h.001"></path><path d="M10 8h.001"></path><path d="M14 8h.001"></path><path d="M18 8h.001"></path><path d="M8 12h.001"></path><path d="M12 12h.001"></path><path d="M16 12h.001"></path><path d="M7 16h10"></path></svg>`,
    alertCircle: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>`,
    fileText: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>`,
    link: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>`
};

// Get icon SVG by name
function getIcon(iconName) {
    return icons[iconName] || icons.fileText;
}

const tocData = [
    {
        "level": 1,
        "title": "1. Wprowadzenie",
        "page": 1,
        "icon": "book"
    },
    {
        "level": 2,
        "title": "Witamy w WATCHPAX 64",
        "page": 1,
        "description": "Przewodnik użytkownika WATCHPAX 64 — kompletne źródło informacji o dedykowanym serwerze multimedialnym Dataton WATCHP..."
    },
    {
        "level": 2,
        "title": "Wprowadzenie do WATCHPAX 64",
        "page": 2,
        "description": "WATCHPAX 64 to dedykowany serwer multimedialny do pracy z Dataton WATCHOUT. Każde urządzenie posiada wbudowaną licenc...",
        "group": "Przegląd",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Akcesoria",
        "page": 3,
        "description": "Zestawienie elementów dołączonych do WATCHPAX 64 oraz akcesoriów dostępnych osobno.",
        "group": "Sprzęt",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Wymiary",
        "page": 4,
        "description": "Wymiary fizyczne i masa urządzenia WATCHPAX 64.",
        "group": "Sprzęt",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Zasilanie",
        "page": 5,
        "description": "Specyfikacja gniazda zasilania WATCHPAX 64.",
        "group": "Sprzęt",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Ekran startowy",
        "page": 6,
        "description": "Ekran startowy jest wyświetlany na wszystkich podłączonych urządzeniach wyświetlających po włączeniu WATCHPAX 64.",
        "group": "Sprzęt",
        "groupOrder": 1,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Warunki środowiskowe",
        "page": 7,
        "description": "Warunki pracy i przechowywania WATCHPAX 64.",
        "group": "Sprzęt",
        "groupOrder": 1,
        "groupItemOrder": 4
    },
    {
        "level": 2,
        "title": "Złącza",
        "page": 8,
        "description": "Przegląd panelu złączy WATCHPAX 64.",
        "group": "Sprzęt",
        "groupOrder": 1,
        "groupItemOrder": 5
    },
    {
        "level": 2,
        "title": "System operacyjny serwera",
        "page": 9,
        "description": "System operacyjny w WATCHPAX 64 został zoptymalizowany i licencjonowany dla tej konkretnej konfiguracji serwera multi...",
        "group": "Oprogramowanie",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "2. Instalacja i obsługa",
        "page": 1,
        "icon": "settings"
    },
    {
        "level": 2,
        "title": "Przed rozpoczęciem użytkowania WATCHPAX 64",
        "page": 1,
        "description": "Przed rozpoczęciem pracy prosimy o dokładne zapoznanie się z instrukcją. Przy odbiorze urządzenia zawsze należy spraw...",
        "group": "Pierwsze kroki",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Wentylacja",
        "page": 2,
        "description": "Przepływ powietrza jest kluczowy dla prawidłowego działania WATCHPAX 64. Nie blokuj przodu ani tyłu urządzenia. W każ...",
        "group": "Pierwsze kroki",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Instalacja",
        "page": 3,
        "description": "Instrukcje instalacji WATCHPAX 64, w tym opcje montażu wolnostojącego i w szafie rack oraz procedury włączania/wyłącz...",
        "group": "Pierwsze kroki",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Szybki start",
        "page": 4,
        "description": "Krótki przewodnik szybkiego uruchomienia WATCHPAX 64.",
        "group": "Obsługa",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Reset WATCHPAX 64",
        "page": 5,
        "description": "Zdarzają się sytuacje, w których konieczny może być reset WATCHPAX 64, na przykład gdy urządzenie zostało uszkodzone ...",
        "group": "Obsługa",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Różne",
        "page": 6,
        "description": "Dodatkowe funkcje i opcje konfiguracji WATCHPAX 64, w tym wyjście audio i sieciowy interfejs WATCHPAX Config.",
        "group": "Dodatkowe funkcje",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "3. Synchronizacja",
        "page": 1,
        "icon": "link"
    },
    {
        "level": 2,
        "title": "Dostęp do WATCHPAX Config",
        "page": 1,
        "description": "Rozpocznij od znalezienia adresu IP urządzenia WATCHPAX 64. Powinien on być widoczny na ekranie powitalnym WATCHOUT, ...",
        "group": "Konfiguracja",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Konfiguracja emulacji EDID",
        "page": 2,
        "description": "Emulacja EDID zapewnia spójną identyfikację wyświetlaczy na wszystkich podłączonych wyjściach.",
        "group": "Konfiguracja",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Włączanie mozaiki",
        "page": 3,
        "description": "Utwórz siatkę mozaiki, aby połączyć wiele wyjść wyświetlania w jedną zunifikowaną powierzchnię.",
        "group": "Zaawansowana konfiguracja",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Synchronizacja sprzętowa",
        "page": 4,
        "description": "Konfiguracja synchronizacji sprzętowej między wieloma urządzeniami WATCHPAX 64 za pomocą karty NVIDIA Quadro Sync II.",
        "group": "Zaawansowana konfiguracja",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 1,
        "title": "4. Gwarancja, zgodność i utylizacja",
        "page": 1,
        "icon": "fileText"
    },
    {
        "level": 2,
        "title": "Ograniczona gwarancja",
        "page": 1,
        "description": "DATATON AB („Dataton\") udziela gwarancji na niniejszy produkt sprzętowy na wady materiałowe i wykonawcze na okres sie...",
        "group": "Aspekty prawne",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Deklaracja zgodności",
        "page": 2,
        "description": "Dataton AB niniejszym oświadcza, że WATCHPAX 64 jest zgodny z poniższymi normami i przepisami.",
        "group": "Aspekty prawne",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Utylizacja",
        "page": 3,
        "description": "Dotyczy wyłącznie Unii Europejskiej i EOG (Norwegia, Islandia i Liechtenstein).",
        "group": "Aspekty prawne",
        "groupOrder": 0,
        "groupItemOrder": 2
    }
];

// Process TOC data into hierarchical structure
function processHierarchy() {
    const chapters = [];
    let currentChapter = null;

    tocData.forEach((item) => {
        if (item.level === 1) {
            const isDisabled = typeof wikiConfig !== 'undefined' && 
                wikiConfig.disabledChapters && 
                wikiConfig.disabledChapters.includes(item.title);

            currentChapter = {
                ...item,
                disabled: isDisabled,
                subsections: []
            };
            chapters.push(currentChapter);
        } else if (item.level === 2 && currentChapter) {
            currentChapter.subsections.push(item);
        }
    });

    return chapters;
}

const chaptersData = processHierarchy();
