// WATCHPAX 64 User Guide - Table of Contents Data
// Auto-generated by build-content.js - DO NOT EDIT DIRECTLY
// Edit the markdown files in /content instead

// SVG Icons (Lucide-style)
const icons = {
    book: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>`,
    settings: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>`,
    layout: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>`,
    monitor: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><line x1="8" y1="21" x2="16" y2="21"></line><line x1="12" y1="17" x2="12" y2="21"></line></svg>`,
    film: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect><line x1="7" y1="2" x2="7" y2="22"></line><line x1="17" y1="2" x2="17" y2="22"></line><line x1="2" y1="12" x2="22" y2="12"></line><line x1="2" y1="7" x2="7" y2="7"></line><line x1="2" y1="17" x2="7" y2="17"></line><line x1="17" y1="17" x2="22" y2="17"></line><line x1="17" y1="7" x2="22" y2="7"></line></svg>`,
    clock: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>`,
    play: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>`,
    sliders: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="21" x2="4" y2="14"></line><line x1="4" y1="10" x2="4" y2="3"></line><line x1="12" y1="21" x2="12" y2="12"></line><line x1="12" y1="8" x2="12" y2="3"></line><line x1="20" y1="21" x2="20" y2="16"></line><line x1="20" y1="12" x2="20" y2="3"></line><line x1="1" y1="14" x2="7" y2="14"></line><line x1="9" y1="8" x2="15" y2="8"></line><line x1="17" y1="16" x2="23" y2="16"></line></svg>`,
    globe: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>`,
    keyboard: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2" ry="2"></rect><path d="M6 8h.001"></path><path d="M10 8h.001"></path><path d="M14 8h.001"></path><path d="M18 8h.001"></path><path d="M8 12h.001"></path><path d="M12 12h.001"></path><path d="M16 12h.001"></path><path d="M7 16h10"></path></svg>`,
    alertCircle: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>`,
    fileText: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>`,
    link: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>`
};

// Get icon SVG by name
function getIcon(iconName) {
    return icons[iconName] || icons.fileText;
}

const tocData = [
    {
        "level": 1,
        "title": "1. Introduction",
        "page": 1,
        "icon": "book"
    },
    {
        "level": 2,
        "title": "Welcome to WATCHPAX 64",
        "page": 1,
        "description": "WATCHPAX 64 User's Guide -- your complete reference for the Dataton WATCHPAX 64 dedicated media server."
    },
    {
        "level": 2,
        "title": "Introduction to WATCHPAX 64",
        "page": 2,
        "description": "WATCHPAX 64 is a dedicated media server for use with Dataton WATCHOUT. Each unit has a built-in WATCHOUT license and ...",
        "group": "Overview",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Accessories",
        "page": 3,
        "description": "A summary of items included with the WATCHPAX 64 and accessories available separately.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Dimensions",
        "page": 4,
        "description": "Physical dimensions and weight of the WATCHPAX 64 unit.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Power",
        "page": 5,
        "description": "Power inlet specifications for the WATCHPAX 64.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Start Up Screen",
        "page": 6,
        "description": "The startup screen is displayed on all connected display devices when the WATCHPAX 64 powers on.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 3
    },
    {
        "level": 2,
        "title": "Environmental",
        "page": 7,
        "description": "Operating and storage conditions for the WATCHPAX 64.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 4
    },
    {
        "level": 2,
        "title": "Connectors",
        "page": 8,
        "description": "Overview of the WATCHPAX 64 connector panel.",
        "group": "Hardware",
        "groupOrder": 1,
        "groupItemOrder": 5
    },
    {
        "level": 2,
        "title": "Media Server Operating System",
        "page": 9,
        "description": "The operating system in WATCHPAX 64 has been optimized and licensed for this specific media server configuration.",
        "group": "Software",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "2. Installation and Operation",
        "page": 1,
        "icon": "settings"
    },
    {
        "level": 2,
        "title": "Before Using Your WATCHPAX 64",
        "page": 1,
        "description": "Please read the manual thoroughly before operation. Always check that the unit has not been damaged in transit when y...",
        "group": "Getting Started",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Ventilation",
        "page": 2,
        "description": "Airflow is critical for the correct operation of WATCHPAX 64. Do not block front or back of the unit. In any installa...",
        "group": "Getting Started",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Installation",
        "page": 3,
        "description": "Instructions for installing the WATCHPAX 64, including standalone and rack mounting options, and power on/off procedu...",
        "group": "Getting Started",
        "groupOrder": 0,
        "groupItemOrder": 2
    },
    {
        "level": 2,
        "title": "Quick Start",
        "page": 4,
        "description": "A brief guide to getting your WATCHPAX 64 up and running.",
        "group": "Operation",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Reset WATCHPAX 64",
        "page": 5,
        "description": "There are occasions when you may want to reset a WATCHPAX 64, for example, if the unit has been corrupted, or if it i...",
        "group": "Operation",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Miscellaneous",
        "page": 6,
        "description": "Additional features and configuration options for the WATCHPAX 64, including audio output and the WATCHPAX Config web...",
        "group": "Additional Features",
        "groupOrder": 2,
        "groupItemOrder": 0
    },
    {
        "level": 1,
        "title": "3. Synchronization",
        "page": 1,
        "icon": "link"
    },
    {
        "level": 2,
        "title": "Accessing WATCHPAX Config",
        "page": 1,
        "description": "Start by finding the IP address of the WATCHPAX 64. It should show on the WATCHOUT splash screen, but if that is unav...",
        "group": "Configuration",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Setting Up EDID Emulation",
        "page": 2,
        "description": "EDID emulation ensures consistent display identification across all connected outputs.",
        "group": "Configuration",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Enabling Mosaic",
        "page": 3,
        "description": "Create a mosaic grid to combine multiple display outputs into a single unified canvas.",
        "group": "Advanced Setup",
        "groupOrder": 1,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Hardware Sync",
        "page": 4,
        "description": "Configure hardware synchronization between multiple WATCHPAX 64 units using the NVIDIA Quadro Sync II card.",
        "group": "Advanced Setup",
        "groupOrder": 1,
        "groupItemOrder": 1
    },
    {
        "level": 1,
        "title": "4. Warranty, Conformity and Disposal",
        "page": 1,
        "icon": "fileText"
    },
    {
        "level": 2,
        "title": "Limited Warranty",
        "page": 1,
        "description": "DATATON AB (\"Dataton\") warrants this hardware product against defects in materials and workmanship for a period of se...",
        "group": "Legal",
        "groupOrder": 0,
        "groupItemOrder": 0
    },
    {
        "level": 2,
        "title": "Declaration of Conformity",
        "page": 2,
        "description": "Dataton AB hereby declares that the WATCHPAX 64 complies with the standards and regulations listed below.",
        "group": "Legal",
        "groupOrder": 0,
        "groupItemOrder": 1
    },
    {
        "level": 2,
        "title": "Disposal",
        "page": 3,
        "description": "Only for European Union and EEA (Norway, Iceland and Liechtenstein).",
        "group": "Legal",
        "groupOrder": 0,
        "groupItemOrder": 2
    }
];

// Process TOC data into hierarchical structure
function processHierarchy() {
    const chapters = [];
    let currentChapter = null;

    tocData.forEach((item) => {
        if (item.level === 1) {
            const isDisabled = typeof wikiConfig !== 'undefined' && 
                wikiConfig.disabledChapters && 
                wikiConfig.disabledChapters.includes(item.title);

            currentChapter = {
                ...item,
                disabled: isDisabled,
                subsections: []
            };
            chapters.push(currentChapter);
        } else if (item.level === 2 && currentChapter) {
            currentChapter.subsections.push(item);
        }
    });

    return chapters;
}

const chaptersData = processHierarchy();
